-- Run this entire script in Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.loans(id uuid primary key default gen_random_uuid(),name text not null default 'Dream Home Loan',total_amount numeric(14,2) not null default 0,annual_rate numeric(7,4) not null default 0,tenure_months integer not null default 240,start_date date not null default current_date,interest_only_months integer not null default 0,emi_mode text not null default 'auto' check(emi_mode in('auto','manual')),manual_emi numeric(14,2) not null default 0,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.borrowers(id uuid primary key default gen_random_uuid(),loan_id uuid not null references public.loans(id) on delete cascade,name text not null,share_amount numeric(14,2) not null default 0,scheduled_emi numeric(14,2) not null default 0,sort_order integer not null default 0);
create table if not exists public.monthly_payments(id uuid primary key default gen_random_uuid(),loan_id uuid not null references public.loans(id) on delete cascade,borrower_id uuid not null references public.borrowers(id) on delete cascade,month_no integer not null,payment_date date,emi_paid numeric(14,2) not null default 0,extra_principal numeric(14,2) not null default 0,unique(loan_id,borrower_id,month_no));
alter table public.loans enable row level security;alter table public.borrowers enable row level security;alter table public.monthly_payments enable row level security;
create policy "public read loans" on public.loans for select using(true);create policy "public read borrowers" on public.borrowers for select using(true);create policy "public read payments" on public.monthly_payments for select using(true);
create policy "owner insert loans" on public.loans for insert to authenticated with check(created_by=auth.uid());create policy "owner update loans" on public.loans for update to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());create policy "owner delete loans" on public.loans for delete to authenticated using(created_by=auth.uid());
create policy "owner insert borrowers" on public.borrowers for insert to authenticated with check(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));create policy "owner update borrowers" on public.borrowers for update to authenticated using(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid())) with check(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));create policy "owner delete borrowers" on public.borrowers for delete to authenticated using(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));
create policy "owner insert payments" on public.monthly_payments for insert to authenticated with check(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));create policy "owner update payments" on public.monthly_payments for update to authenticated using(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid())) with check(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));create policy "owner delete payments" on public.monthly_payments for delete to authenticated using(exists(select 1 from public.loans l where l.id=loan_id and l.created_by=auth.uid()));
alter publication supabase_realtime add table public.loans;alter publication supabase_realtime add table public.borrowers;alter publication supabase_realtime add table public.monthly_payments;
